name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: install packages
      run: make install
    - name: lint
      run: make lint
    - name: test
      run: make test
    - name: format
      run: make format
    - name: Model Evaluation
      run: make evaluation
    # below code just test whether app is deployed successfully or not ..o/p cant be checked
    - uses: streamlit/streamlit-app-action@v0.0.3
      with:
        app-path: prediction/app.py
        ruff: true
    - name: deploy
      run: make deploy
    # - name: Deploy code
    #   env:
    #     SERVER_IP: localhost
    #     PORT: 8600
    #   run: streamlit run prediction/app.py --server.address localhost  --server.port 8600
    # - name: start local server
    #   run: python -m http.server 8600